// Book data for the reading shelf. Loaded by reading/index.html; sets window.booksData.
// Optional: rating (1–5), review (short comment).

window.booksData = [
  {
    id: '1',
    title: 'Ball Lightning',
    author: 'Cixin Liu',
    readDate: '2026-01-03',
    isbn: 9780765394071,
    type: 'print',
    numberOfPages: 384,
    genres: ['Science Fiction'],
    rating: 4.3,
    review: 'Massive fan of Cixin Liu. Not my favourite, but still couldn\'t stop reading it. My favourite is still The Dark Forest though.',
    description: 'When Chen\'s parents are incinerated before his eyes by a blast of ball lightning, he devotes his life to cracking the secret of mysterious natural phenomena. His search takes him to stormy mountaintops, an experimental military weapons lab, and an old Soviet science station.\n\nThe more he learns, the more he comes to realize that ball lightning is just the tip of an entirely new frontier in particle physics. Although Chen\'s quest provides a purpose for his lonely life, his reasons for chasing his elusive quarry come into conflict with soldiers and scientists who have motives of their own: a beautiful army major with an obsession with dangerous weaponry, and a physicist who has no place for ethical considerations in his single-minded pursuit of knowledge.',
  },
  {
    id: '2',
    title: 'Rendezvous with Rama',
    author: 'Arthur C. Clarke',
    readDate: '2026-01-10',
    isbn: 9781857231588,
    type: 'print',
    numberOfPages: 246,
    genres: ['Science Fiction'],
    rating: 4.4,
    review: 'Finally found a print version of this, after hearing it recommended so many times. Did not disappoint. Loved the focus on discovery and exploration. Easy short read that gave me so much context for how some of my favourites were inspired.',
    description: 'Rama is a vast alien spacecraft that enters the Solar System, A perfect cylinder some fifty kilometres long, spinning rapidly, racing through space, Rama is a technological marvel, a mysterious and deeply enigmatic alien artifact. It is Mankind\'s first visitor from the stars and must beinvestigated...',
  },
  {
    id: '3',
    title: 'Children of Time',
    author: 'Adrian Tchaikovsky',
    readDate: '2026-01-18',
    isbn: 9781447273301,
    type: 'print',
    numberOfPages: 629,
    genres: ['Science Fiction'],
    rating: 4.6,
    review: 'Wow. This took me a little to get into at first, but what a world he has created here. Apparently there is more to this series, but I feel so satisfied with the ending, I don\'t know if I need it. It\'s not to the level of a Cixin Liu or Neal Stephenson, for my tastes, but I loved it and will recommend to others.',
    description: 'The last remnants of the human race left a dying Earth, desperate to find a new home. Following their ancestor\'s star maps, they discovered the greatest treasure of a past age - a world terraformed and prepared for human life.\n\nBut all is not right in this new Eden. The planet is not waiting for them, pristine and unoccupied. New monsters have turned it from a refuge into mankind\'s worst nightmare. Now two civilisations are on a collision course and must fight to survive. As the fate of humanity...',
  },
  {
    id: '4',
    title: 'Starter Villain',
    author: 'John Scalzi',
    readDate: '2026-01-21',
    isbn: 9781509835416,
    type: 'print',
    numberOfPages: 278,
    genres: ['Science Fiction', 'Comedy', 'Thriller'],
    rating: 3.7,
    review: 'Flew through this in a couple days. Doesn\'t come close to being great, but I don\'t think it tries to. Just a silly, fun story that I was excited to see where it led. I\'d say it probably started better than it ended, but regardless, I had a lot of fun with it.',
    description: 'Inheriting your uncle\'s supervillain business is more complicated than you might think. Particularly when you discover who\'s running the place.\n\nCharlie\'s life is going nowhere fast. A divorced substitute teacher living with his cat in a house his siblings want to sell, all he wants is to open a pub downtown, if only the bank will approve his loan.\n\nThen his long-lost uncle Jake dies and leaves his supervillain business (complete with island volcano lair) to Charlie.\n\nBut becoming a supervillain isn\'t all giant laser death rays and lava pits. Jake had enemies, and now they\'re coming after Charlie. His uncle might have been a stand-up, old-fashioned kind of villain, but these are the real thing: rich, soulless predators backed by multinational corporations and venture capital.\n\nIt\'s up to Charlie to win the war his uncle started against a league of supervillains. But with unionized dolphins, hyper-intelligent talking spy cats, and a terrifying henchperson at his side, going bad is starting to look pretty good.\n\nIn a dog-eat-dog world...be a cat.',
  },
  {
    id: '5',
    title: 'Liar\'s Poker',
    author: 'Michael Lewis',
    readDate: '2026-01-17',
    isbn: 9780393338690,
    type: 'audio',
    numberOfPages: 310,
    durationHours: 10,
    durationMinutes: 16,
    genres: ['Non-fiction', 'Finance', 'Memoir'],
    rating: 3.9,
    review: 'I\'ve already read Barbarians at the Gate, When Genius Failed, and other books involving the same people. This was fascinating to learn more about them, and an overall fun look at the culture of Wall Street at the time.',
    description: 'In 1986, before Michael Lewis became the best-selling author of The Big Short, Moneyball, and Flash Boys, he landed a job at Salomon Brothers, one of Wall Street\'s premier investment firms.\n\nDuring the next three years, Lewis rose from callow trainee to New York- and London-based bond salesman, raking in millions for the firm and cashing in on a modern-day gold rush. Liar\'s Poker is the culmination of those heady, frenzied years - a behind-the-scenes look at a unique and turbulent time in American business. This new audio edition, produced by the same team that produces his number one podcast Against the Rules, is unabridged, read by the author, and features archival news clips from the era, original scoring and sound effects, as well as a bonus episode from the companion podcast.\n\nFrom the frat-boy camaraderie of the 41st-floor trading room to the killer instinct that made ambitious young men gamble everything on a high-stakes game of bluffing and deception, Liar\'s Poker is both "the funniest book on Wall Street I\'ve ever read" (Tom Wolfe) and the launchpad for Michael Lewis\' storied career.',
  },
  {
    id: '6',
    title: 'The Sixth Extinction',
    author: 'Elizabeth Kolbert',
    readDate: '2026-01-27',
    isbn: 9780805099799,
    type: 'print',
    numberOfPages: 326,
    genres: ['Non-fiction', 'Science', 'Environment'],
    rating: 4.1,
    review: 'A shockingly dark look at the impact of humanity on our planet. I read this at the recommendation of a friend, so had no idea what I was getting myself into, besides the obvious hint of the title. While not exactly a page turner, it was a fascinating read that gave me a bit more appreciation for animals/species that I rarely considered.',
    description: 'Over the last half a billion years, there have been five mass extinctions, when the diversity of life on earth suddenly and dramatically contracted. Scientists around the world are currently monitoring the sixth extinction, predicted to be the most devastating extinction event since the asteroid impact that wiped out the dinosaurs. This time around, the cataclysm is us.\n\nIn The Sixth Extinction, two-time winner of the National Magazine Award and New Yorker writer Elizabeth Kolbert draws on the work of scores of researchers in half a dozen disciplines, accompanying many of them into the field: geologists who study deep ocean cores, botanists who follow the tree line as it climbs up the Andes, marine biologists who dive off the Great Barrier Reef. She introduces us to a dozen species, some already gone, others facing extinction, including the Panamian golden frog, staghorn coral, the great auk, and the Sumatran rhino.\n\nThrough these stories, Kolbert provides a moving account of the disappearances occurring all around us and traces the evolution of extinction as concept, from its first articulation by Georges Cuvier in revolutionary Paris up through the present day. The sixth extinction is likely to be mankind\'s most lasting legacy; as Kolbert observes, it compels us to rethink the fundamental question of what it means to be human.',
  },
  {
    id: '7',
    title: 'A Man For All Markets',
    author: 'Edward O. Thorp',
    readDate: '2026-01-30',
    isbn: 9781400067961,
    type: 'audio',
    numberOfPages: 416,
    durationHours: 16,
    durationMinutes: 30,
    genres: ['Memoir', 'Finance', 'Mathematics'],
    rating: 4.4,
    review: 'Listening to this shortly after reading Feynman\'s book made the parallels hard to miss. Hearing his childhood story made me almost forget I was reading the book of a legendary quantitative investor. Another clear genius, that seemed obsessed with play and simply figuring things out.',
    description: 'A child of the Great Depression, legendary mathematician Edward O. Thorp invented card counting, proving the seemingly impossible: that you could beat the dealer at the blackjack table. As a result he launched a gambling renaissance. His remarkable success--and mathematically unassailable method--caused such an uproar that casinos altered the rules of the game to thwart him and the legions he inspired. They barred him from their premises, even put his life in jeopardy. Nonetheless, gambling was forever changed.\n\nThereafter, Thorp shifted his sights to "the biggest casino in the world" Wall Street. Devising and then deploying mathematical formulas to beat the market, Thorp ushered in the era of quantitative finance we live in today. Along the way, the so-called godfather of the quants played bridge with Warren Buffett, crossed swords with a young Rudy Giuliani, detected the Bernie Madoff scheme, and, to beat the game of roulette, invented, with Claude Shannon, the world\'s first wearable computer.\n\nHere, for the first time, Thorp tells the story of what he did, how he did it, his passions and motivations, and the curiosity that has always driven him to disregard conventional wisdom and devise game-changing solutions to seemingly insoluble problems. An intellectual thrill ride, replete with practical wisdom that can guide us all in uncertain financial waters, A Man for All Markets is an instant classic--a book that challenges its readers to think logically about a seemingly irrational world.',
  },
  {
    id: '8',
    title: 'Life, The Universe, and Everything',
    author: 'Douglas Adams',
    readDate: '2026-02-07',
    isbn: 9781529034547,
    type: 'print',
    numberOfPages: 210,
    genres: ['Science Fiction', 'Comedy'],
    rating: 4.2,
    review: 'Another hilarious read in the Hitchikers Guide To The Galaxy series. I had to import this one into Vietnam as I couldn\'t find it anywhere, well worth it to continue the ridiculous adventures of Arthur Dent. Already got books 4 and 5 ready to go.',
    description: 'In Life, the Universe and Everything, the third title in Douglas Adams\' blockbusting sci-fi comedy series, The Hitchhiker\'s Guide to the Galaxy, Arthur Dent finds himself enlisted to prevent a galactic war.\n\nFollowing a number of stunning catastrophes, which have involved him being alternately blown up and insulted in ever stranger regions of the Galaxy, Arthur Dent is surprised to find himself living in a cave on prehistoric Earth. However, just as he thinks that things cannot get possibly worse, they suddenly do. An eddy in the space-time continuum lands him, Ford Prefect, and their flying sofa in the middle of the cricket ground at Lord\'s, just two days before the world is due to be destroyed by the Vogons.\n\nEscaping the end of the world for a second time, Arthur, Ford, and their old friend Slartibartfast embark (reluctantly) on a mission to save the whole galaxy from fanatical robots. Not bad for a man in his dressing gown...',
  },
  {
    id: '9',
    title: 'Grinding It Out: The Making of McDonald\'s',
    author: 'Ray Kroc',
    readDate: '2026-02-08',
    isbn: 9781250127501,
    type: 'print',
    numberOfPages: 206,
    genres: ['Business', 'Biography'],
    rating: 3.8,
    review: '"Even in his last few years when he was confined to a wheelchair, he still went to the office in San Diego nearly every day". This passion and obsession is clear from the book, the sacrifices he talks of from him and all of the early people. Nothing I would ever want to do. I love business, but I want more out of my life than just that. This perspective re-reading it in my early 30s is likely different from when I first read it in my early 20s. Anyway, a great re-read of a fascinating character. I kind of wished for a bit more detail, but I also love hearing things in his words and perspective. I\'m a big proponent of decentralised management, others like Charles Koch in his book Good Profit push this idea strongly. It is cool to see Ray Kroc emphasise this too, it never stood out to me in my initial reading as a solopreneur.',
    description: 'Few entrepreneurs can claim to have radically changed the way we live, and Ray Kroc is one of them. His revolutions in food-service automation, franchising, shared national training, and advertising have earned him a place beside the men and women who have founded not only businesses, but entire empires. But even more interesting than Ray Kroc the business man is Ray Kroc the man. Not your typical self-made tycoon, Kroc was fifty-two years old when he opened his first franchise. In Grinding It Out, you\'ll meet the man behind McDonald\'s, one of the largest fast-food corporations in the world with over 32,000 stores around the globe.\n\nIrrepressible enthusiast, intuitive people person, and born storyteller, Kroc will fascinate and inspire you on every page.',
  },
  {
    id: '10',
    title: 'Seven Tenths of a Second: Life, Leadership and Formula 1',
    author: 'Zak Brown',
    readDate: '2026-02-13',
    isbn: 9798217184781,
    type: 'audio',
    numberOfPages: 288,
    durationHours: 5,
    durationMinutes: 58,
    genres: ['Business', 'Biography', 'Sports'],
    rating: 2.8,
    review: 'I probably should not be surprised as an F1 fan, but Zak came across rather arrogant in this. The whole thing felt more like a lengthy podcast than a biography. But it was fascinating to see stories of his rise and the success of McLaren F1. He\'s clearly a highly accomplished guy with a lot to learn from, and I did enjoy this overall as I had no idea how he entered the world of F1 or what his background was.',
    description: 'The enthralling account from Zak Brown, CEO of McLaren Racing, tackling life and leadership in the high-stakes world of Formula 1.\n\nZak Brown led one of F1\'s most iconic teams to the 2024 Constructors\' Championship after over a quarter of a century. McLaren Racing\'s return to the top has gone hand in hand with a well-earned reputation for team harmony, fairness, and loyalty. Now Zak\'s chosen to invite readers in to experience it for themselves, with all the honesty, conviction, and good humor he has brought to leading one of the most storied teams in motorsport back to the front of the grid.\n\nSeven Tenths of a Second will take readers behind the scenes and into the paddock and boardroom to explore how the team has fought its way back to the top under Zak\'s leadership, and shine a light on what it takes to succeed in a sport that constantly pushes the boundaries of technology, innovation, and engineering.\n\nSharing stories and lessons acquired through a life in motorsport, Seven Tenths of a Second will offer unprecedented insights into life at McLaren Racing and beyond.',
  },
  {
    id: '11',
    title: 'Walt Disney: An American Original',
    author: 'Bob Thomas',
    readDate: '2026-02-13',
    isbn: 9780786860272,
    type: 'print',
    numberOfPages: 379,
    genres: ['Business', 'Biography', 'Film'],
    rating: 4.7,
    review: 'I absolutely adored this book and story. What an incredible guy that just focused on creating the absolute best of what he did knowing the money will follow. His relentless pursuit after repeated failures, backstabbings and betrayals is so inspiring. His obsession with the customer, not distributors or critics, is exactly what we\'ve seen with the rise of DTC brands and probably the idea behind Disney+. And his unwavering confidence that the best short, film, show, park, or product will win clearly shows why I grew up with such a love of Disney. Practically every penny they had, and then some, went into producing better and better media. And while still millions of dollars in debt, he decided why not build an amusement park too because he thought he could do that better too. What an absolutely fascinating and inspiring guy, and a great book covering the whole story. I really loved this one.',
    description: 'The story of Walt Disney\'s life--told as no other book can!\n\nWalt Disney is an American hero. From Mickey Mouse to Disneyland, he changed the face of American culture. His is a success story like no a man who developed animated film into an art form and made a massive contribution to the folklore of the world.\n\nAfter years of research, respected Hollywood biographer Bob Thomas produced a definitive biography of the man behind the legend of the unschooled cartoonist from Kansas City who when bankrupt on his first movie venture and developed into the genius who produced unmatched works of animation, and ultimately was the creative spirit of an international entertainment empire that has enchanted generations. Complete with a collection of rare photographs, Walt An American Original is a fascinating and inspirational work that captures the spirit of Walt Disney.',
  },
  {
    id: '12',
    title: 'So Long, and Thanks for All the Fish',
    author: 'Douglas Adams',
    readDate: '2026-02-15',
    isbn: 9781529034554,
    type: 'print',
    numberOfPages: 177,
    genres: ['Science Fiction', 'Comedy'],
    rating: 4.4,
    review: 'More hilariousness from the adventures of Arthur Dent and new character Fenchurch. I laughed out loud in the middle of the airport reading the biscuit story. I think I\'d put this as my third favourite in the series. The first two are my clear favourites, and the next two are harder to place, but having just finished this I think I\'d put it higher than book #3. I\'ve loved them all though and would recommend all.',
    description: 'So Long, and Thanks for All the Fish is the fourth installment in Douglas Adams\' bestselling cult classic, the Hitchhiker\'s Guide to the Galaxy \'trilogy\'.\n\nThis edition includes exclusive bonus material from the Douglas Adams archives, and an introduction by Neil Gaiman.\n\nThere is a knack to flying. The knack lies in learning how to throw yourself at the ground and miss. It\'s not an easy thing to do and Arthur Dent thinks he\'s the only human who\'s been able to master this nifty little trick - until he meets Fenchurch, the girl of his dreams.\n\nFenchurch knows how the world could be made a good and happy place. Unfortunately, she\'s forgotten. Convinced that the secret lies within God\'s Final Message to His Creation they go in search of it.\n\nAnd, in a dramatic break with tradition, actually find it...',
  },
  {
    id: '13',
    title: 'The Wright Brothers: A Biography',
    author: 'Fred C. Kelly',
    readDate: '2026-02-16',
    isbn: 9780486260563,
    type: 'print',
    numberOfPages: 384,
    genres: ['History', 'Biography', 'Aviation'],
    rating: 4.5,
    review: 'What an amazing story of two pioneers of the modern world. Of course I\'d heard of the Wright brothers, but I had no idea of the depth of the story. Reading this feels like a guidebook to the scientific method. The ignorance of the media is hilariously absurd, reminds me of Walt Disney\'s lesson that distributors/networks/media don\'t care until the public cares. But the Wrights just got on with it, not a care, they were builders and experimenters not fame seekers. The book ending is rather bleak though. Years wasted fighting patents, even knowing they won, feels like it must have been torture. The Smithsonian attempting to discredit them and promote Langley instead was disgusting and reminded me of a similar story with George Stephenson (the father of railways) when he created a miners\' safety lamp and the Royal Society accused him of stealing it from a celebrated scientist because he was “only” an engineer. Of course we know it worked out in the end, but it doesn\'t make it any less awful to know these legends (or more so Orville as his brother had earlier died) were put through this. Still, an incredible story and exciting read that I flew through in a couple days.',
    description: 'In this fascinating, highly readable biography, Fred C. Kelly, a former newspaperman, author, and an old friend of the Wrights, tells the story of the two brilliant, dedicated, flight-obsessed bicycle mechanics from Ohio who first realized mankind\'s age-old dream of conquering the skies. Long considered the definitive Wright biography (the manuscript was read and approved by Orville Wright), this book recounts the Wrights\' small-town boyhood, their early interest in all things mechanical, the establishment of the Wright Cycle Shop, and the complete behind-the-scenes story of how they designed, built, tested, and flew (December 1903) the first "Flyer."\n\nEnhanced with sixteen rare photographs, Mr. Kelly\'s engaging account avoids minute technical description, yet describes simply and clearly the technological innovations that enabled the two brothers to succeed where so many others had failed. Anyone interested in the mechanics of flight or early aviation will find this volume a splendid introduction to the Wright brothers and their epochal achievement.',
  },
  {
    id: '14',
    title: 'Sol Price: Retail Revolutionary & Social Innovator',
    author: 'Robert E. Price',
    readDate: '2026-02-19',
    isbn: 9780988680609,
    type: 'print',
    numberOfPages: 223  ,
    genres: ['Business', 'Biography'],
    rating: 3.5,
    review: 'In terms of writing, I found this a little dull. Like a book report. With a lot of admiration for the subject (his father, rather expected). Which is rather a shame because it seems there is so much to learn from Sol Price, and books from people that learned from and copied him such as Sam Walton\'s Made In America, frankly, do it better. Regardless, Sol\'s story was absolutely fascinating to read, as well as his impact on the retail industry. While this book is hardly brimming with ideas, there is still plenty to learn. And as Charlie Munger has said, I think the real power may just be in taking the simple ideas seriously.',
    description: 'Sol Retail Revolutionary and Social Innovator, recounts the extraordinary life of a man who profoundly impacted the shopping habits of consumers in the United States and throughout much of the world. Written by Sol\'s son Robert Price, this narrative - part biography and part memoir - provides a unique insight into his father\'s life. Sol\'s retail success was grounded in an absolute commitment to bringing the best value to his customers. Just as importantly, he insisted on paying high wages and good benefits, including health care, to his employees. He had a real conscience satisfied only by giving the best deal he could to just about everyone. As a retail revolutionary, Sol\'s creative brilliance changed the way we shop, first with FedMart in 1954, the retail format copied by Walmart, Kmart, and Target in 1962, and then, with the Price Club, the warehouse club format adopted by Costco and Sam\'s Club in 1983. Self-service shopping in large florescent-lit buildings has become part of the American culture and is now the predominant mode of shopping though most of the world.',
  },
  {
    id: '15',
    title: 'Mostly Harmless',
    author: 'Douglas Adams',
    readDate: '2026-02-22',
    isbn: 9781509808380,
    type: 'print',
    numberOfPages: 272  ,
    genres: ['Science Fiction', 'Comedy'],
    rating: 4,
    review: 'Another fun, enjoyable story to wrap up the official Hitchhiker\'s Guide To The Galaxy series. Not my favourite, but I completely disagree with skipping it. Still far better than not reading a Douglas Adams book. I found the Random character annoying, to say the least. But Arthur ending up enjoying life as a simple sandwich maker? Perfect. Ford\'s adventures through the newly corporate offices also pure fun. And the ending? Partly hate it, partly think it just fits.',
    description: 'Mostly Harmless is the fifth and final part in Douglas Adams\' much-loved cult classic series. Arthur Dent hadn\'t had a day as bad as this since the Earth had been blown up. Depressed and alone, Arthur finally settles on the small planet Lamuella and becomes a sandwich maker. Looking forward to a quiet life, his plans are thrown awry by the unexpected arrival of his daughter.There\'s nothing worse than a frustrated teenager with a copy of the Hitchhiker\'s Guide to the Galaxy in their hands. When she runs away - Arthur goes after her determined to save her from the horrors of the universe. After all - he\'s encountered most of them before...',
  },
  {
    id: '16',
    title: 'This Mortal Coil: A History of Death',
    author: 'Andrew Doig',
    readDate: '2026-02-27',
    isbn: 9781526624390,
    type: 'print',
    numberOfPages: 384,
    genres: ['History', 'Science'],
    rating: 3.9,
    review: 'I\'ve been lucky enough to have given little thought to death until reading Derren Brown\'s Happy several years ago. His thoughts surmised from Epicurus on death adding meaning to life, made sense to me. In total contrast to my reading of How Not To Die. Though, acceptance of death is not the same as not wanting to live. Regardless, this book caught my interest at a local bookstore. What I found was a love letter to epidemiology and the scientific method. And I can\'t help but feel the same way. What is naturally a very dark book, felt oddly light and positive. The writing felt approachable like Sapiens but briefer. I came away feeling appreciative of how unlikely I am to die of a plague or scurvy or just being born. But also the inevitableness of death and disease. And you know, I am okay with that.',
    description: 'Causes of death have changed irrevocably across time. In the course of a few centuries we have gone from a world where disease or violence were likely to strike anyone at any age, and where famine could be just one bad harvest away, to one where in many countries excess food is more of a problem than a lack of it. Why have the reasons we die changed so much? How is it that a century ago people died mainly from infectious disease, while today the leading causes of death in industrialised nations are heart disease and stroke? And what do changing causes of death reveal about how previous generations have lived?\n\nUniversity of Manchester Professor Andrew Doig provides an eye-opening portrait of death throughout history, looking at particular causes - from infectious disease to genetic disease, violence to diet - who they affected, and the people who made it possible to overcome them. Along the way we hear about the long and torturous story of the discovery of vitamin C and its role in preventing scurvy; the Irish immigrant who opened the first washhouse for the poor of Liverpool, and in so doing educated the public on the importance of cleanliness in combating disease; and the Church of England curate who, finding his new church equipped with a telephone, started the Samaritans to assist those in emotional distress.\n\nThis Mortal Coil is a thrilling story of growing medical knowledge and social organisation, of achievement and, looking to the future, of promise.',
  },
  {
    id: '17',
    title: 'And Another Thing...',
    author: 'Eoin Colfer',
    readDate: '2026-03-05',
    isbn: 9780718155148,
    type: 'print',
    numberOfPages: 340,
    genres: ['Science Fiction', 'Comedy'],
    rating: 3.0,
    review: 'I have such mixed feelings on this book. On one hand, it is noticeably not Douglas Adams\' writing. On the other, I just finished the original trilogy of five, and was already longing for more adventures of Arthur Dent and Ford Prefect. I\'d say, this almost but doesn\'t quite hit the spot. And that I\'m such a fanboy of this universe, I enjoyed it anyway. The guide entries were sometimes too excessive. The humour was not close to as good, but did have me laughing at times. It felt more like good fan fiction. Glad I gave it a shot anyway.',
    description: 'AN ENGLISHMAN\'S CONTINUING SEARCH THROUGH SPACE AND TIME FOR A DECENT CUP OF TEA...\n\nArthur Dent\'s accidental association with that wholly remarkable book The Hitchhiker\'s Guide to the Galaxy has not been entirely without incident.\n\nArthur has traveled the length, breadth, and depth of known, and unknown, space. He has stumbled forward and backward through time. He has been blown up, reassembled, cruelly imprisoned, horribly released, and colorfully insulted more than is strictly necessary. And of course Arthur Dent has comprehensively failed to grasp the meaning of life, the universe, and everything.\n\nArthur has finally made it home to Earth, but that does not mean he has escaped his fate.\n\nArthur\'s chances of getting his hands on a decent cuppa have evaporated rapidly, along with all the world\'s oceans. For no sooner has he touched down on the planet Earth than he finds out that it is about to be blown up...again.\n\nAnd Another Thing...is the rather unexpected, but very welcome, sixth installment of the Hitchhiker\'s Guide to the Galaxy series. It features a pantheon of unemployed gods, everyone\'s favorite renegade Galactic President, a lovestruck green alien, an irritating computer, and at least one very large slab of cheese.',
  },
  {
    id: '18',
    title: 'The Anarchy: The East India Company, Corporate Violence, and the Pillage of an Empire',
    author: 'William Dalrymple',
    readDate: '2026-03-11',
    isbn: 9781635573954,
    type: 'audio',
    numberOfPages: 576,
    durationHours: 15,
    durationMinutes: 43,
    genres: ['History', 'Politics'],
    rating: 4.1,
    review: 'I was blissfully unaware of this story. Of course, I was aware of Britain taking over India, especially as a Brit myself. But that it was a publicly traded company that did so? I purchased this book because of my love of business, expecting the story of how one of England\'s most successful corporations was built. Instead, this was a history of how the East India Company accumulated their power, their land, their position through wars and battles. The business was whatever was there. Not at all what I was expecting, but highly fascinating. Quite a long audiobook, but kept me engaged the whole time. It did make me wonder, what\'s the difference between a country and a corporation? Both are concepts we created. If it\'s wrong for a corporation to do this, how is it right for a country to do it? Does being a representative of land make it right? I lean toward neither should, but it\'s an interesting question to sit with.',
    description: 'The story of how the East India Company took over large swaths of Asia, and the devastating results of the corporation running a country.\n\nIn August 1765, the East India Company defeated the young Mughal emperor and set up, in his place, a government run by English traders who collected taxes through means of a private army.\n\nThe creation of this new government marked the moment that the East India Company ceased to be a conventional company and became something much more unusual: an international corporation transformed into an aggressive colonial power. Over the course of the next 47 years, the company\'s reach grew until almost all of India south of Delhi was effectively ruled from a boardroom in the city of London.',
  },
  {
    id: '19',
    title: 'Les Schwab Pride in Performance: Keep It Going',
    author: 'Les Schwab',
    readDate: '2026-03-13',
    isbn: 9780892881512,
    type: 'print',
    numberOfPages: 239,
    genres: ['Business', 'Biography'],
    rating: 4.3,
    review: 'Starting this book, it was immediately obvious that Les wasn\'t particularly a great writer. It took a minute to build up, and felt random and repetitive at times. But I quickly realised how little that mattered. What this book does is share the story of a wonderful business that was (is?) brilliantly managed. It\'s like a wholesome version of Ray Kroc\'s Grinding It Out. His management principles just make sense, he\'s clearly another fan of decentralised management, prioritises the stores (actually making the money) over the head office, and is the antithesis to everything I\'ve read in Barbarians At The Gate. His profit sharing program is lovely, and a testament to the importance of incentives that Charlie Munger has repeated so many times. I found this book inspiring and educational. This feels like how I want to do business.',
    description: 'This is the story of Les Schwab and his company. He tells how he started in the tire business and shares with the reader his ideas on building a successful business through building successful employees. Les is a businessman not a writer, but like in business, he gets his points across. He is the undisputed king of the tire business in the Pacific Northwest. His is the largest independent tire business in the world and he makes it look easy. If you are in business or want to be in business you must read this book.',
  },
  {
    id: '20',
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    readDate: '2026-03-16',
    isbn: 9780007491568,
    type: 'print',
    numberOfPages: 227,
    genres: ['Classics', 'Science Fiction'],
    rating: 4.0,
    review: 'This is a book about the beauty and wonder of books. It\'s about the dangers of a life wasted in algorithms and feeds, like TikTok, long before their existence. Clarisse seems so ordinary, yet so odd in this world. It reminds me of how odd taxi drivers look at me, when I decide to spend the entire drive looking out of the window just enjoying the experience, instead of nose diving into my phone. And it reminds me of my books being rejected by customs because they\'re not on a pre-approved list. In some ways, it is a far-fetched dystopian world, in others, it seems awfully familiar. Now for me, I found it awfully flowery. That is intentional, clearly, and it is beautiful and flowing in a way, I could find myself getting caught in it also. But at other times my autistic brain was screaming come on, get to the point. That\'s more of a reflection on my preferences, than the author.',
    description: 'The terrifyingly prophetic novel of a post-literate future.\n\nGuy Montag is a fireman. His job is to burn books, which are forbidden, being the source of all discord and unhappiness. Even so, Montag is unhappy; there is discord in his marriage. Are books hidden in his house? The Mechanical Hound of the Fire Department, armed with a lethal hypodermic, escorted by helicopters, is ready to track down those dissidents who defy society to preserve and read books.\n\nThe classic dystopian novel of a post-literate future, Fahrenheit 451 stands alongside Orwell\'s 1984 and Huxley\'s Brave New World as a prophetic account of Western civilization\'s enslavement by the media, drugs and conformity.\n\nBradbury\'s powerful and poetic prose combines with uncanny insight into the potential of technology to create a novel which, decades on from first publication, still has the power to dazzle and shock.',
  },
  {
    id: '21',
    title: 'Runnin\' Down a Dream: How to Thrive in a Career You Actually Love',
    author: 'Bill Gurley',
    readDate: '2026-03-20',
    isbn: 9780593799666,
    type: 'print',
    numberOfPages: 272,
    durationHours: 7,
    durationMinutes: 58,
    genres: ['Business', 'Self Help'],
    rating: 3.4,
    review: 'I say this all the time, but I did not realise what this book was. I saw Bill Gurley, something about a dream, and thought BUY. What I found was a great book that is about 15 years too late for me. Not that it\'s ever too late to find a career you love, but that I\'ve already done it. I was the weird teenager with the 30 second career guidance meeting, where I told them exactly what I would do (and was right). Bill\'s book is a mix of practical tips for pulling your ideal career out of your head, and inspirational stories of others that have done just this. I\'d already heard a few of these stories before in other books and podcasts, but even hearing them again was rather inspiring. It was also great to hear his story, which is what I\'d originally wanted. But my habit of buying books without knowing what they are is more of a reflection on me, than the books themselves. This is a great read and I\'d strongly recommend it for someone that is unsure of what the future looks like for them.',
    description: 'Life is a use-it-or-lose-it proposition. Shouldn’t you spend it doing something you love? This book will teach you how to find your dream job and avoid a career you’ll regret—from a leading venture capitalist, based on his viral college talk.\n\nFor many young people, the path to success feels like a conveyor belt—onto the next test, the next application, the next college—without ever stopping to ask what do I actually want to do with my life? Parents know the pressure can be overwhelming, yet the system pushes everyone forward anyway.\n\nAfter college Bill Gurley landed a job at a famous tech company. It should have been a dream come true—but he was surprisingly bored. So, Gurley leapt into the unknown, eventually finding his place in the world of venture capital, the beginning of a remarkable investing career.\n\nIt turns out, Gurley’s happy ending is rare. Nearly six in ten people would do things differently if they could start over. This is the trap of “career regret.” So how can we avoid it? What can we learn from people at the top of their fields who love what they do? The culmination of Gurley’s decade-long project to unpack the components of success, Runnin’ Down a Dream identifies six principles to flourish in your chosen\n\n1. Chase your curiosity\n2. Hone your craft\n3. Develop mentors in your field\n4. Embrace your peers\n5. Go where the action is\n6. Always give backThese timeless principles add up to a playbook not just for success, but a purpose-filled life. Written in Gurley’s straight-talk voice and revealing the captivating stories of industry titans like talent agent Lorrie Bartlett, restaurateur Danny Meyer, and sports executive Sam Hinkie, Runnin’ Down a Dream will inspire a new generation to find their place in the world, while offering a much-needed rebuttal to the idea that hustle and happiness are incompatible.',
  },
  {
    id: '22',
    title: 'Genome: The Autobiography of a Species in 23 Chapters',
    author: 'Matt Ridley',
    readDate: '2026-03-30',
    isbn: 9780060894085,
    type: 'print',
    numberOfPages: 344,
    genres: ['Science'],
    rating: 4.2,
    review: 'Ridley is a wonderful storyteller, hence why I purchased this over Mukherjee\'s The Gene: An Intimate History, which I was equally tempted by, but won over by the fact I enjoyed Ridley\'s How Innovation Works so much more. It did not disappoint. I am not well versed enough to critique the science or accuracy of this. But as a story, as ideas, as concepts to ponder; it was exactly what I was looking for. It left me a bit in wonder of how incredible life is. I\'m just a system of 3 billion base pairs, somehow. As someone that read The Selfish Gene many years ago, forgetting much of it, it wasn\'t so much shocking as it was fascinating to read more on the topic. As for the politics, I saw others complaining about this, I couldn\'t care less. Partly because I similarly lean toward free (or at least free-er) market principles. Partly because I enjoy hearing people\'s opinions. For me, I\'d say a fascinating read and a topic I\'d like to dive deeper into, most likely Isaacson\'s Code Breaker and Mukherjee\'s The Gene.',
    description: '“Ridley leaps from chromosome to chromosome in a handy summation of our ever increasing understanding of the roles that genes play in disease, behavior, sexual differences, and even intelligence. . . . . He addresses not only the ethical quandaries faced by contemporary scientists but the reductionist danger in equating inheritability with inevitability.” — The New Yorker The genome\'s been mapped. But what does it mean? Matt Ridley\'s Genome is the book that explains it what it is, how it works, and what it portends for the future Arguably the most significant scientific discovery of the new century, the mapping of the twenty-three pairs of chromosomes that make up the human genome raises almost as many questions as it answers. Questions that will profoundly impact the way we think about disease, about longevity, and about free will. Questions that will affect the rest of your life. Genome offers extraordinary insight into the ramifications of this incredible breakthrough. By picking one newly discovered gene from each pair of chromosomes and telling its story, Matt Ridley recounts the history of our species and its ancestors from the dawn of life to the brink of future medicine. From Huntington\'s disease to cancer, from the applications of gene therapy to the horrors of eugenics, Ridley probes the scientific, philosophical, and moral issues arising as a result of the mapping of the genome. It will help you understand what this scientific milestone means for you, for your children, and for humankind.',
  },
  {
    id: '23',
    title: 'Foundation',
    author: 'Isaac Asimov',
    readDate: '2026-04-03',
    isbn: 9780008117498,
    type: 'print',
    numberOfPages: 231,
    genres: ['Science Fiction'],
    rating: 4.4,
    review: 'Complete side note: I had to get this printed on demand because my international order attempt got blocked at customs. Anyway, this felt (and is) more like 5 short, connected stories, than a book. I don\'t particularly love that. If it were 5 long stories that expanded far more, I think I would have preferred it personally. But this book was an absolute page turner for me. It just feels rather incomplete, like reviewing a TV show based on the pilot alone (even if the pilot was awesome). The ideas are fantastic, the writing is deliberately simple - the opposite of Ray Bradbury\'s flowery style. But as monumentally impactful as this book has been, I can\'t rate it as high or even equal to Children Of Time or the Remembrance of Earth\'s Past trilogy, all of which are focused on big ideas too, but feel so much more fleshed out. Still, I feel the need to stop writing my thoughts so I can start the next book.',
    description: 'The FOUNDATION series is Isaac Asimov\'s iconic masterpiece. Unfolding against the backdrop of a crumbling Galactic Empire, the story of Hari Seldon\'s two Foundations is a lasting testament to an extraordinary imagination, one whose unprecedented scale shaped Science Fiction as we know it today. The Galactic Empire has prospered for twelve thousand years. Nobody suspects that the heart of the thriving Empire is rotting, until psychohistorian Hari Seldon uses his new science to foresee its terrible fate. Exiled to the desolate planet Terminus, Seldon establishes a colony of the greatest minds in the Empire, a Foundation which holds the key to changing the fate of the galaxy. However, the death throes of the Empire breed hostile new enemies, and the young Foundation\'s fate will be threatened first.',
  },
  {
    id: '24',
    title: 'This Is for Everyone: The Unfinished Story of the World Wide Web',
    author: 'Tim Berners-Lee',
    readDate: '2026-04-05',
    isbn: 9780374612467,
    type: 'audio',
    numberOfPages: 400,
    durationHours: 11,
    durationMinutes: 39,
    genres: ['Technology', 'Biography'],
    rating: 4.3,
    review: 'Wow, I thoroughly enjoyed this, especially the first few chapters. Stephen Fry as narrator was simply the cherry on top. I\'d heard the highlights of Tim Berners-Lee\'s story before, but I never knew the full story. This is the guy that invented the World Wide Web, then gave it away for free (or at least convinced CERN to do so). More Woz than Jobs. This is a nerd in the best sense of the word, with clear interests in an open internet, not ruled by a few corporate overlords. What I loved was the story, where the idea came from, what other projects were around, how it started and grew, etc. The chapters about what he\'s building at Solid were less fascinating, but I did enjoy his perspective and would love to see something like that standardised. Overall, I really enjoyed this, especially in audiobook form, if only more biographies were narrated by Stephen Fry.',
    description: 'The most influential inventor of the modern world, Sir Tim Berners-Lee is a different kind of visionary. Born in the same year as Bill Gates and Steve Jobs, Berners-Lee famously distributed his invention, the World Wide Web, for no commercial reward. Its widespread adoption changed everything – transforming humanity into the first digital species. Through the web, we live, work, dream and connect.\n\nIn this intimate memoir, Berners-Lee tells the story of his iconic invention, exploring how it launched a new era of creativity and collaboration, while unleashing a commercial race that today imperils democracies and polarizes public debate. Filled with his characteristic optimism, technical insight and wry humour, this is a book about the power of technology – both to fuel our worst instincts and to profoundly shape our lives for the better.\n\nAs the rapid development of artificial intelligence heralds a new era of innovation, Berners-Lee is the perfect guide to the crucial decisions ahead – and provides a gripping, in-the-room account of the rise of the online world. Peppered with rich anecdote and amusing reflections, This is For Everyone is an essential read for understanding our times, and a bold manifesto for advancing humanity\'s future.',
  },
  {
    id: '25',
    title: 'Foundation and Empire',
    author: 'Isaac Asimov',
    readDate: '2026-04-07',
    isbn: 9780008117504,
    type: 'print',
    numberOfPages: 230,
    genres: ['Science Fiction'],
    rating: 4.5,
    review: 'This is not a better book than the first one. It doesn\'t introduce the universe, Hari Seldon, the big concepts and ideas, etc. But with them already introduced in book one, this was such an enjoyable read and had me far more hooked than the first. The Mule was exactly what this series needed, totally unexpected, and a much deeper drama around a single character. This book essentially resolved all my issues with the first one. I liked it so much, I\'m already 46 pages into the next one.',
    description: 'Foundation and Empire tells the incredible story of a new breed of man who create a new force for galactic government. Thus, the Foundation hurtles into conflict with the decadent, decrepit First Empire. In this struggle for power amid the chaos of the stars, man stands at the threshold of a new, enlightened life which could easily be put aside for the old forces of barbarism. The Foundation novels of Isaac Asimov constitute what is very likely the most famed epic in all of science-fiction.',
  },
  {
    id: '26',
    title: 'Second Foundation',
    author: 'Isaac Asimov',
    readDate: '2026-04-10',
    isbn: 9780008117511,
    type: 'print',
    numberOfPages: 227,
    genres: ['Science Fiction'],
    rating: 4.6,
    review: 'This is my favourite of the trilogy. In the same way that the finale is the best episode of a TV show (except GOT or Dexter or...). It made the whole series better. The ending especially was perfect, I decided there and then that I wouldn\'t ever need the sequels. Though, maybe I\'ll be tempted by the prequel someday. Now I get the hype.',
    description: 'When the First Foundation was conquered by a force Seldon had not foreseen - the overwhelming power of a single individual, a mutant called the Mule - the second Foundation was forced to reveal its existence and, infinitely worse, a portion of its power. One man understood the shifting patterns of the inhabited cosmos. This was Hari Seldon, the last great scientist of the First Empire.\n\nThe mathematics of psychohistory enabled Seldon to predict the collapse of the Empire and the onset of an era of chaos and war. To restore civilization in the shortest possible time, Seldon set up two Foundations. The First was established on Terminus in the full daylight of publicity. But the Second, at the other end of the galaxy , took shape behind a veil of total silence.\n\nBecause the Second Foundation guards the laws of psychohistory, which are valid only so long as they remain secret. So far the second Foundation\'s location, its most closely guarded secret of all, has been kept hidden. The Mule and the remnants of the First Foundation will do anything to discover it. This is the story of the Second Foundation.',
  },
  {
    id: '27',
    title: 'Fooling Some of the People All of the Time',
    author: 'David Einhorn',
    readDate: '2026-04-25',
    isbn: 9780470481547,
    type: 'audio',
    numberOfPages: 448,
    durationHours: 13,
    durationMinutes: 20,
    genres: ['Finance', 'Business'],
    rating: 4.0,
    review: 'This is basically a drama set in the financial world. Most shocking of all is that they seem to have gotten away with it? At least by the end of the book. Fact check: It looks like the stock eventually met its downfall in 2010 - 3 years after the book published. As someone that actively follows financial news and reads multiple similar books (i.e. When Genius Failed, Barbarians At The Gate, Liars Poker, etc), this was absolutely fascinating. For most regular people, unlike a Michael Lewis book which anyone will find interesting, it was probably a bit too detailed. For me though, it was awesome, kind of felt similar to reading Confidence Game about Bill Ackman, except more detailed. Also highlights how much simpler Buffetts "buy and hold great companies" philosophy seems. Maybe the richest investor in the world is onto something.',
    description: 'A rare look inside the world of activist hedge funds from one of this country\'s top investors.\n\nIn 2002, David Einhorn, the president of Greenlight Capital, gave a speech at a charity investment conference and was asked to share his best investment idea. He described his reasons why Greenlight had sold short the shares of Allied Capital, a leader in the private finance industry. What followed was a firestorm of controversy.\n\nAllied responded with a Washington, D.C. style spin-job - attacking Einhorn and disseminating half-truths and outright lies. Undeterred by the spin-job and lies, Greenlight continued its research after the speech and discovered Allied\'s behavior was far worse than Einhorn ever suspected. Fooling Some of the People All of the Time is the gripping chronicle of this saga, and this edition contains all new updates from the author.\n\nMinute by minute, it delves deep inside Wall Street, showing how the $6-billion hedge fund Greenlight Capital conducts its investment research and detailing the maneuvers of an unscrupulous company. Along the way, you\'ll witness feckless regulators, compromised politicians, and the barricades our capital markets have erected against exposing misconduct from important Wall Street customers.\n\nGoes behind the scenes to detail the truth about investing, short selling, and the politics of business Shows the failings of Wall its investment banks, analysts, journalists, and especially our government regulators Offers insights into the battles surrounding hedge funds Reveals the immense difficulties that prevent the government from sanctioning politically connected companies At its most basic level, Allied Capital is the story of Wall Street at its worst. But the story is much bigger than one little-known company. Fooling Some of the People All of the Time is an important call for effective law enforcement, free speech, and fair play.',
  },
  {
    id: '28',
    title: 'A Brief History of Intelligence',
    author: 'Max Solomon Bennett',
    readDate: '2026-04-30',
    isbn: 9780008560133,
    type: 'print',
    numberOfPages: 432,
    genres: ['Science', 'History'],
    rating: 4.7,
    review: 'Wow, for such a technical subject, I absolutely tore through this book. Truly fascinating. Bennett\'s breakthroughs seem incredibly well thought out (to a guy that knows nothing). His reasoning that we ought to study biological intelligence in the creation of artificial intelligence seems logical, and he intelligently presents the counterargument himself in the book. We do not fly like birds, we thought we should, we studied it, but that\'s not how planes... nor helicopters... nor rockets work. "We" being the royal we of humanity, nothing I\'ve contributed to. So clearly there are alternative ways to doing things. But then, that doesn\'t mean not studying it. I came away from this book thinking, someone is going to pay this guy millions of dollars to think about this for them. Then I realised he has his own AI company. Makes sense really.',
    description: 'The entirety of the human brain’s 4-billion-year story can be summarised as the culmination of five evolutionary breakthroughs, starting from the very first brains, all the way to the modern human brains. Each breakthrough emerged from new sets of brain modifications, and equipped animals with a new suite of intellectual faculties.\n\nThese five breakthroughs are the organising map to this book, and they make up our itinerary for our adventure back in time. Each breakthrough also has fascinating corollaries to breakthroughs in AI. Indeed, there will be plenty of such surprises along the way. For instance: the innovation that enabled AI to beat humans in the game of Go – temporal difference reinforcement learning – was an innovation discovered by our fish ancestors over 500 million years ago. The solutions to many of the current mysteries in AI – such as ‘common sense’ – can be found in the tiny brain of a mouse. Where do emotions come from? Research suggests that they may have arisen simply as a solution to navigation in ancient worm brains. Unravelling this evolutionary story will reveal the hidden features of human intelligence and with them, just how your mind came to be.',
  },
  {
    id: '29',
    title: 'Starship Titanic',
    author: 'Terry Jones',
    readDate: '2026-05-04',
    isbn: 9781035001453,
    type: 'print',
    numberOfPages: 196,
    genres: ['Science Fiction', 'Comedy'],
    rating: 3.9,
    review: 'Pure fun. It\'s not Douglas Adams - less absurdist, less sharp, less funny. But then, he didn\'t write it. That didn\'t stop me leaping at it when I saw the bright green book with his name on it at the bookstore. Instead, it\'s written by one of the creators of Monty Python, which is really an "enough said" type statement. It\'s short, catchy, and fun. Much better done than Eoin Colfer\'s attempt in "And Another Thing". I would have read it in one sitting, if not for 99.98% of my time being on my recent wedding.',
    description: 'At the centre of the galaxy, a vast, unknown civilisation is preparing for an event of epic proportions - the launch of the greatest, most gorgeous, most technologically advanced spaceship ever built - the Starship Titanic.\n\nAn Earthling would see the ship as something really really big, but rather less provincial onlookers would recognise it as the design of Leovinus, the galaxy\'s most renowned architect. Before the launch, Leovinus is having one last little look round and begins to find that things just aren\'t right; poor workmanship, cybersystems out of control, robots walking into doors. How could this have happened? The Starship Titanic is THE SHIP THAT CANNOT POSSIBLY GO WRONG...\n\nWhile the galaxy\'s media looks on the following morning, hugely, magnificently, the fabulous ship eases away from the construction dock, picks up speed, sways a little, wobbles a bit, veers wildly and, just before it can do untold damage to everything around it, appears to undergo SMEF (Spontaneous Massive Existence Failure). In just ten seconds, the whole, stupendous enterprise is over. And our story has just begun...',
  },
  {
    id: '30',
    title: 'Hyperion',
    author: 'Dan Simmons',
    readDate: '2026-05-16',
    isbn: 9781399609500,
    type: 'print',
    numberOfPages: 496,
    genres: ['Science Fiction', 'Fantasy'],
    rating: 3.2,
    review: 'I can\'t overstate how much I hated the beginning of Hyperion. While the priests story was quite interesting as a concept, it was an absolute chore to read. Thankfully, it did get better. The soldiers story was great, the scholars story was near perfect. But I still continually found Simmons\' writing to be in the way of my enjoyment. That\'s probably just me, I shared similar thoughts on Fahrenheit 451, but at least that felt poetically beautiful, this just felt annoying. Though, that may be because descriptive prose is about as useless to me as gourmet plating for a blind person. Regardless, I loved the scholars story, but no, I would not recommend this. Oh, and it\'s a cliffhanger ending. Well, not really, it\'s more like 500 pages of foreplay. Seems like most of the story is in the second book.',
    description: 'It is the 29th century and the universe of the Human Hegemony is under threat. Invasion by the warlike Ousters looms, and the mysterious schemes of the secessionist AI TechnoCore bring chaos ever closer.\n\nOn the eve of disaster, with the entire galaxy at war, seven pilgrims set forth on a final voyage to the legendary Time Tombs on Hyperion, home to the Shrike, a lethal creature, part god and part killing machine, whose powers transcend the limits of time and space. The pilgrims have resolved to die before discovering anything less than the secrets of the universe itself.',
  },
  {
    id: '31',
    title: 'The 38 Letters From J.D. Rockefeller To His Son',
    author: 'Unknown',
    readDate: '2026-05-18',
    isbn: 9788199968523,
    type: 'print',
    numberOfPages: 196,
    genres: ['Business'],
    rating: 1,
    review: 'I kept seeing Vietnamese versions of this book in Fahasa, then kept mentioning to my (now) wife how I wish they had it in English. So she imported it for me as a birthday gift. Hence, the "now wife". Unfortunately, while reading this book, I couldn\'t help but notice the irregular spelling errors, misused tenses, phrases that had me questioning "did they really speak like this back then?" (no), and later a reference that had me questioning "did Citibank really exist back then?" (it didn\'t). Well, a little research quickly revealed that following in the footsteps of Think and Grow Rich, Rich Dad Poor Dad, and many others in this space - the book\'s a fake. Rockefeller never wrote a single one of the 40 letters in this edition.\n\nStill, it was a mildly interesting read. Repetitive, certainly. But honestly, the philosophy shared is generally sound. I\'m more left pondering, why do it? Money presumably, but who knows. I find it rather fascinating. I\'d say good job really, it\'s quite compellingly done. I particularly liked the letters regarding J.P. Morgan and Andrew Carnegie. Knowing they\'re fake ruins the illusion, but it\'s fun to consider.',
    description: 'The 38 letters written by Rockefeller to his son imparting his perspectives, ideology, and wisdom to his son.',
  },
  {
    id: '32',
    title: 'Misbehaving: The Making of Behavioral Economics',
    author: 'Richard H. Thaler',
    readDate: '2026-05-19',
    isbn: 9780393352795,
    type: 'audio',
    numberOfPages: 358,
    durationHours: 9,
    durationMinutes: 4,
    genres: ['Economics', 'Psychology'],
    rating: 3.5,
    review: 'Short version: Read Thinking Fast and Slow instead.\n\nThaler can\'t quite decide if this a biography or a behavioural economics book, and it suffers for it. I found this enjoyable, in the same way a religious person re-reading the bible would. I didn\'t particularly learn anything new, some of the stories and examples were interesting, but they rarely stick with me after completing a book.\n\nMy favourite was the financial chapter, but that\'s just an interest of mine. I completely agree with his opinions on the efficient marketing hypothesis, though his explanation of the market turning against LTCM is rather misleading, excessive leverage was their problem (see: When Genius Failed).\n\nMost interesting was the amount of opposition his seemingly obvious ideas received from some of the leading economists in the world. However, that\'s probably a bias on my behalf from having context today that they never have, as the consensus has clearly caught up. Anyway, fun read, better than Predictably Irrational, easier to read that Thinking Fast and Slow, but nowhere near as informative.',
    description: 'A founding father of behavioral economics (Chicago Tribune), Richard H. Thaler has spent his career investigating the radical notion that the central agents in the economy are humans error-prone but predictable individuals. Once dismissed by economists as an amusing sideshow, the study of human miscalculations and their effects on markets now drives efforts to make better decisions in our lives, our businesses, and our governments. Misbehaving spans Thaler\'s decades as a leader in this transformation and reveals how the insights of behavioral economics can help everyone think more intelligently about their time and their money.\n\nWith relatable examples from everyday life investments, household spending to television game show dilemmas and the NFL draft, Misbehaving offers a present-at-the-creation account of Thaler\'s battle to upend traditional economic thinking. As readable as Freakonomics, as provocative as Thinking, Fast and Slow, Misbehaving is a singular look into profound human foibles one that will have readers retooling their grocery lists and retirement strategies, and lead managers to rethink every aspect of their business.',
  },
  {
    id: '33',
    title: 'We Are Legion (We Are Bob)',
    author: 'Dennis E. Taylor',
    readDate: '2026-05-26',
    isbn: 9781680680584,
    type: 'audio',
    durationHours: 9,
    durationMinutes: 56,
    genres: ['Science Fiction'],
    rating: 4.2,
    review: 'The Audible algorithm has been pushing me towards this for like a year now, and rightfully so, it\'s exactly my type of book. The narration is wonderful, normally I prefer to read sci-fi, but listening this time was a real joy. The story is great, playing on the concept of immortality among other things, though more of an entertaining style like Andy Weir than say Cixin Liu. It\'s funny too, not Douglas Adams funny (obviously), but bright enough with a few good one-liners. My only real complaint is it\'s a bit short, which isn\'t much of a complaint at all when there\'s a whole series of books to dive into. Already started the second.',
    description: 'Bob Johansson has just sold his software company and is looking forward to a life of leisure. There are places to go, books to read, and movies to watch. So it\'s a little unfair when he gets himself killed crossing the street.\n\nBob wakes up a century later to find that corpsicles have been declared to be without rights, and he is now the property of the state. He has been uploaded into computer hardware and is slated to be the controlling AI in an interstellar probe looking for habitable planets. The stakes are high: no less than the first claim to entire worlds. If he declines the honor, he\'ll be switched off, and they\'ll try again with someone else. If he accepts, he becomes a prime target. There are at least three other countries trying to get their own probes launched first, and they play dirty.\n\nThe safest place for Bob is in space, heading away from Earth at top speed. Or so he thinks. Because the universe is full of nasties, and trespassers make them mad - very mad.',
  },
  {
    id: '34',
    title: 'Born to Be Wired',
    author: 'John Malone',
    readDate: '2026-05-31',
    isbn: 9781668051535,
    type: 'print',
    numberOfPages: 432,
    genres: ['Business', 'Biography'],
    rating: 4.4,
    review: 'This is a masterclass in creating shareholder value told through a series of stories where Malone did, well, exactly that. The antithesis to the Elon Musk approach, Malone is firmly against excessive risk, immediately opening with a story concluding with "never bet the whole farm… on anything. No deal is ever worth doing that".\n\nBut risk, he took. This is essentially a dealmaking biography. Not sales and negotiations, but autistic detail focused deals. Perfect for my similarly autistic brain.\n\nI came into this with a vague understanding of Malone\'s TCI story, having read The Outsiders a few years back. What I lacked was the specifics, and the whole Liberty Media story afterwards.\n\nMalone used partnerships, acquisitions, and an Amazon-like approach to fast growth to establish market positioning in the cable world. Then leveraged this to negotiate equity in Discovery, BET, QVC, and others which later became another multi-billion dollar company known as Liberty Media. Notably the owners of F1 today, or at least, notably to me.\n\nHonestly, despite being a book entirely about cable and media deals, it\'s not about that at all. It\'s about capital allocation. A niche Berkshire Hathaway, if you will. And that\'s, well, entirely my sort of thing. Not that I have billions of dollars to make a play at F1, but that doesn\'t make the ideas any less useful.',
    description: 'Although millions have been touched by the technologies and content he made possible, John Malone is a stranger to most people. In Born to Be Wired, this legendary "cable cowboy" shares stories from behind the scenes of the most transformative deals in media, entertainment, and technology. He recounts the extraordinary saga of how America was wired—how a single copper strand evolved from a rural TV-antenna service into a high-speed backbone powering the internet and clearing the path for Amazon, Facebook, and Google.\n\nMalone offers an insider\'s account of launching television\'s first cable networks and the strategy behind era-defining mergers, from Warner Bros. Discovery to Live Nation Entertainment. His Liberty Media ventures, including Formula One, have delivered long-term returns often compared to Berkshire Hathaway.\n\nMore than a business story, this is a personal reflection—from a quiet kid with a mechanic\'s curiosity to a media visionary confronting the costs and consequences of disruption in an industry he helped reshape. Trained at the storied Bell Labs and gifted with a mathematical mind, Malone saw patterns in complexity. Where others saw chaos he saw systems—and reconfigured companies with the precision of an engineer, unlocking value no one else could see.',
  },
  {
    id: '35',
    title: 'For We Are Many',
    author: 'Dennis E. Taylor',
    readDate: '2026-06-01',
    isbn: 9781680680591,
    type: 'audio',
    durationHours: 8,
    durationMinutes: 59,
    genres: ['Science Fiction'],
    rating: 4.2,
    review: 'More of the first book, feels like a direct continuation, which is exactly what the second book in a series should feel like. Already onto the third. Great book, great narration. Poor Homer.',
    description: 'Bob Johansson didn\'t believe in an afterlife, so waking up after being killed in a car accident was a shock. To add to the surprise, he is now a sentient computer and the controlling intelligence for a Von Neumann probe.\n\nBob and his copies have been spreading out from Earth for 40 years now, looking for habitable planets. But that\'s the only part of the plan that\'s still in one piece. A system-wide war has killed off 99.9 percent of the human race; nuclear winter is slowly making the Earth uninhabitable; a radical group wants to finish the job on the remnants of humanity; the Brazilian space probes are still out there, still trying to blow up the competition; and the Bobs have discovered a spacefaring species that sees all other life as food.\n\nBob left Earth anticipating a life of exploration and blissful solitude. Instead he\'s become a sky god to a primitive native species, the only hope for getting humanity to a new home, and possibly the only thing that can prevent every living thing in the local sphere from ending up as dinner.',
  },
  {
    id: '36',
    title: 'All These Worlds',
    author: 'Dennis E. Taylor',
    readDate: '2026-06-04',
    isbn: 9781680680607,
    type: 'audio',
    durationHours: 7,
    durationMinutes: 56,
    genres: ['Science Fiction'],
    rating: 4.2,
    review: 'Lovely finish to seemingly the original trilogy. I like this universe, it\'s less hard science than some of my favourites, but as bright and paced as Andy Weir books, with some nerdy nostalgia like Ernest Cline. I binged the first 3 audiobooks in about a week. Very tempted to start the 4th, but the 3rd wrapped up nicely, so I\'ll get back to some non-fiction first.',
    description: 'Being a sentient spaceship really should be more fun. But after spreading out through space for almost a century, Bob and his clones just can\'t stay out of trouble.\n\nThey\'ve created enough colonies so humanity shouldn\'t go extinct. But political squabbles have a bad habit of dying hard, and the Brazilian probes are still trying to take out the competition. And the Bobs have picked a fight with an older, more powerful species with a large appetite and a short temper.\n\nStill stinging from getting their collective butts kicked in their first encounter with the Others, the Bobs now face the prospect of a decisive final battle to defend Earth and its colonies. But the Bobs are less disciplined than a herd of cats, and some of the younger copies are more concerned with their own local problems than defeating the Others.\n\nYet salvation may come from an unlikely source. A couple of eighth-generation Bobs have found something out in deep space. All it will take to save the Earth and perhaps all of humanity is for them to get it to Sol — unless the Others arrive first.',
  },
  {
    id: '37',
    title: 'Ringworld',
    author: 'Larry Niven',
    readDate: '2026-06-07',
    isbn: 9780575077027,
    type: 'print',
    numberOfPages: 288,
    genres: ['Science Fiction'],
    rating: 4.4,
    review: 'Considering this is essentially a book on the rise and fall, mostly the fall, of civilisations - it\'s awfully bright. It\'s fun, watching them romp around Ringworld exploring this fallen masterpiece of engineering far beyond their own understanding.\n\nEven the build up was fun to me. I loved the earth setting, the character introductions, even the story prior to ever reaching Ringworld. No performative prose getting in the way of a good story.\n\nBeing genetically bred for luck is, well, absurd. But it\'s fun conceptually to follow Louis\' reasoning as he explained it. Felt very Interstellar in a, this makes absolutely no sense, but a lot of sense within this story.',
    description: 'The artefact is a circular ribbon of matter six hundred million miles long and ninety million miles in radius. Pierson\'s puppeteers, the aliens who discovered it, are understandably wary of encountering the builders of such an immense structure and have assembled a team of two humans, a mad puppeteer and a kzin, a huge cat-like alien, to explore it. But a crash landing on the vast edifice forces the crew on a desperate and dangerous trek across the Ringworld.',
  },
  {
    id: '38',
    title: '1929',
    author: 'Andrew Ross Sorkin',
    readDate: '2026-06-14',
    isbn: 9780241479421,
    type: 'audio',
    numberOfPages: 592,
    durationHours: 13,
    durationMinutes: 30,
    genres: ['Economics', 'Finance', 'History'],
    rating: 3.7,
    review: '1929 is a moment by moment play of the stock market crash that led to the great depression. Sorkin similarly wrote Too Big To Fail on the 2008 crash, which I\'ve yet to read.\n\nIt may only be me, but I found Sorkin\'s narration annoying. It did not help, that right before I\'d been listening to the wonderful Ray Porter. But in a book. Where one man. Ends every sentence. Like a trailer. Is very annoying. Thankfully, 2x speed masked this.\n\nThe book includes several people involved and related to the 1929 crash. Some seemingly treated unfairly, some excessively fairly, and my new favourite Jesse Livermore. Not that I know anything of him, but what a character. He bet big, made big, then lost everything. Beautifully tragic.\n\nRegardless, the book was interesting. Not riveting. It\'s not Barbarians at the Gate, you can put it down. But it gives a detailed look at what Sorkin believes is essentially greed causing a crash. Same as \'08. Maybe even the same with the hype cycle of todays market.\n\nWas it greed? Excess leverage? Speculation (I guess, that\'s another word for greed). Misaligned incentives? To me, it looked like all of these. But all I know is what I read in the book.',
    description: 'From the bestselling author of Too Big to Fail, "the definitive history of the 2008 banking crisis," comes a spellbinding narrative of the most infamous stock market crash in history. With the depth of a classic history and the drama of a thriller, 1929 unravels the greed, blind optimism, and human folly that led to an era-defining collapse—one with ripple effects that still shape our society today.\n\nIn 1929, the world watched in shock as the unstoppable Wall Street bull market went into a freefall, wiping out fortunes and igniting a depression that would reshape a generation. But behind the flashing ticker tapes and panicked traders, another drama unfolded—one of visionaries and fraudsters, titans and dreamers, euphoria and ruin.\n\nWith unparalleled access to historical records and newly uncovered documents, New York Times bestselling author Andrew Ross Sorkin takes readers inside the chaos of the crash, behind the scenes of a raging battle between Wall Street and Washington and the larger-than-life characters whose ambition and naivete in an endless boom led to disaster. The dizzying highs and brutal lows of this era eerily mirror today\'s world—where markets soar, political tensions mount, and the fight over financial influence plays out once again.\n\nThis is not just a story about money. 1929 is a tale of power, psychology, and the seductive illusion that "this time is different." It\'s about disregarded alarm bells, financiers who fell from grace, and skeptics who saw the crash coming—only to be dismissed until it was too late.\n\nHailed as a landmark book, Too Big to Fail reimagined how financial crises are told. Now, with 1929, Sorkin delivers an immersive, electrifying account of the most pivotal market collapse of all time—with lessons that remain as urgent as ever. More than just a history, 1929 is a crucial blueprint for understanding the cycles of speculation, the forces that drive financial upheaval, and the warning signs we ignore at our peril.',
  },
  {
    id: '39',
    title: 'Insisting on the Impossible',
    author: 'Victor K. McElheny',
    readDate: '2026-06-19',
    isbn: 9780738201900,
    type: 'print',
    numberOfPages: 544,
    genres: ['Biography', 'Business', 'Science'],
    rating: 4.3,
    review: 'Edwin Land is up there as one of my personal favourites of the many biographies I\'ve read over the years. A scientist, a showman, a dreamer. Land didn\'t settle for marginal improvement, he demanded innovation.\n\nEveryone knows Polaroid. But it all started with solving headlight glare, then sunglasses, camera filters, optical devices for the military, spy planes, spy satellites, and yes, instant cameras. That\'s not even mentioning his Retinex theory of colour vision, which he theorised in his free time.\n\nI can\'t help but feel a reminder of Ed Thorp\'s autobiography. A genius turning his intellectual prowess into a business created through deliberate experimentation.\n\nI\'ve got little more than a rudimentary knowledge of chemistry. The book far exceeds my understanding. It\'s far too detailed at times. But it gave me an appreciation, a scope of the effort that went into every step of discovery along the way. A case study in Edisonian product creation.\n\nThis is in complete contrast to my love of capital allocation. I loved John Malone\'s book. I\'ll read everything I can find on Charlie Munger. They feel more me. Patterns, systems, that all makes sense to me. But I truly admire an attitude of creating something new, better, defining.\n\nSometimes it flops. Polavision sounded like a beautifully innovative horror story. But I doubt Land regretted it. The creation of defining products was why he did it. Not the market success. And what if they didn\'t oust Land? Would he have created another market leading product? Would they still have declined into eventual bankruptcy?\n\nOn completion, I feel admiration for Land. I\'m not that guy. I\'m not a showman. I can\'t risk it all for an idea, then let the market prove me right (or wrong). But I can\'t help but feel Land\'s approach, much like Disney\'s total disregard for costs or risks, feels almost poetic. Because at the end of the day, maybe it\'s worth it. Not the balance sheet, not the returns, just the wonder of creating something new.',
    description: 'If a single life exemplifies the inner drive that fires a great inventor, it is the life of Edwin Land. The major innovations that he was able to achieve in photography, optics, industry, and science policy carry priceless lessons for readers today.\n\nInsisting on the Impossible is the first full-scale biography of this Magellan of modern technology. Victor McElheny reveals the startling scope and daring spirit of Land\'s scientific and entrepreneurial genius. Second only to Edison in the number of patents he received (535), Land built a modest enterprise into a gigantic "invention factory," turning out not only polarizers and the first instant cameras, but also high-speed and X-ray film, identification systems, 3-D and instant movies, and military devices for night vision and aerial reconnaissance.\n\nAs a scientist, Land developed a new theory of color vision; as a science advisor to Eisenhower during the Cold War he spearheaded the development of the U-2 spyplane and helped design NASA.\n\nBehind these protean achievements was a relentless curiosity, a magical public presence, and a willful optimism that drew him again and again to conquer "the impossible." In an era when these qualities are needed more than ever, this masterly biography will speak to anyone involved or interested in business, science, photography, educational reform of government.',
  },
  {
    id: '40',
    title: 'The Zoologist\'s Guide to the Galaxy',
    author: 'Arik Kershenbaum',
    readDate: '2026-06-28',
    isbn: 9781984881960,
    type: 'print',
    numberOfPages: 368,
    genres: ['Science'],
    rating: 4.2,
    review: 'This purchase is once again showing, I far too often judge books by their covers. Or titles, in this case. Aliens, check. Douglas Adams reference, check. Buy.\n\nThankfully, I was far from disappointed. One of my favourite reads of the year is Max S. Bennett\'s A Brief History of Intelligence. This book is one and the same. Both highlight the beauty of evolution, only Dr. Arik Kershenbaum does it to hypothesise how that might similarly influence the form and behaviour of aliens, as opposed to artificial intelligence.\n\nWhile some may be disappointed by the skepticism and hedging throughout, it\'s far better to ground the speculations in scientific reasoning.\n\nThe end result isn\'t that aliens are green things with flying saucers, it\'s that they\'ll be similarly influenced by evolution as animals on Earth. And that means certain things are likely (e.g. being social) and certain things are unlikely (e.g. running at the speed of light).\n\nA very fun, easy read. Nothing groundbreaking, but it gives you a real sense of wonderment about animals and evolution, like watching a David Attenborough documentary. Life.',
    description: 'From a noted Cambridge zoologist, a wildly fun and scientifically sound exploration of what alien life must be like, using universal laws that govern life on Earth and in space.\n\nScientists are confident that life exists elsewhere in the universe. Yet rather than taking a realistic approach to what aliens might be like, we imagine that life on other planets is the stuff of science fiction. The time has come to abandon our fantasies of space invaders and movie monsters and place our expectations on solid scientific footing.\n\nBut short of alien\'s landing in New York City, how do we know what they are like? Using his own expert understanding of life on Earth and Darwin\'s theory of evolution--which applies throughout the universe--Cambridge zoologist Dr. Arik Kershenbaum explains what alien life must be like: how these creatures will move, socialize, and communicate. For example, by observing fish whose electrical pulses indicate social status, we can see that other planets might allow for communication by electricity. As there was evolutionary pressure to wriggle along a sea floor, Earthling animals tend to have left/right symmetry; on planets where creatures evolved mid-air or in soupy tar they might be lacking any symmetry at all.\n\nMight there be an alien planet with supersonic animals? A moon where creatures have a language composed of smells? Will aliens scream with fear, act honestly, or have technology? The Zoologist\'s Guide to the Galaxy answers these questions using the latest science to tell the story of how life really works, on Earth and in space.',
  },
  {
    id: '41',
    title: 'The Demon-Haunted World',
    author: 'Carl Sagan',
    readDate: '2026-07-17',
    isbn: 9780345409461,
    type: 'audio',
    durationHours: 17,
    durationMinutes: 23,
    genres: ['Science'],
    rating: 4.3,
    review: '"A fire-breathing dragon lives in my garage... I neglected to mention that she\'s an invisible dragon... but this dragon floats in the air... the invisible fire is also heatless."\n\nI picked up this audiobook because I\'d heard this story before and couldn\'t stop smiling at how perfect it is. The book was more wonderful stories and examples, just like this.\n\nI\'m not someone that grew up with Carl Sagan. I\'d pretty much never heard of him, except seeing internet culture fawn over him. But I did read Cosmos a few years ago, which I do remember enjoying. And this book, I\'d probably say I\'d enjoyed even more, though that could be recency bias.\n\nMy only problem with it, which was really my wife\'s problem more than mine, was that I couldn\'t stop reciting all the good points he made: "This is SOOO good, honey.... honey.... you know how...".\n\nBut really a fun read. Felt rather like preaching to the choir, but the choir loves being preached to, that\'s why they\'re in the choir. Now I feel like going to watch some old Derren Brown shows, not that he\'s ever referenced, just that it\'s so similar in exposing frauds.',
    description: 'How can we make intelligent decisions about our increasingly technology-driven lives if we don\'t understand the difference between the myths of pseudoscience and the testable hypotheses of science? Pulitzer Prize-winning author and distinguished astronomer Carl Sagan argues that scientific thinking is critical not only to the pursuit of truth but to the very well-being of our democratic institutions.\n\nCasting a wide net through history and culture, Sagan examines and authoritatively debunks such celebrated fallacies of the past as witchcraft, faith healing, demons, and UFOs. And yet, disturbingly, in today\'s so-called information age, pseudoscience is burgeoning with stories of alien abduction, channeling past lives, and communal hallucinations commanding growing attention and respect. As Sagan demonstrates with lucid eloquence, the siren song of unreason is not just a cultural wrong turn but a dangerous plunge into darkness that threatens our most basic freedoms.',
  },
  {
    id: '42',
    title: 'The Rise and Fall of the Dinosaurs: A New History of a Lost World',
    author: 'Steve Brusatte',
    readDate: '2026-08-02',
    isbn: 9781509830091,
    type: 'print',
    numberOfPages: 320,
    genres: ['Science', 'History'],
    rating: 4.2,
    review: 'I\'d purchased this as a gift for a friend already into the series, then picked up a copy for myself too because… dinosaurs. This is a topic where my prior knowledge consists of watching all of the Jurassic Park movies.\n\nThe book was a light, enjoyable read. My friend noted it felt rather like it was written for YA, but I think it could be summed as being clearly "pop science". Not to be confused with bad science, which is typical of pop-sci. Clearly expert written, but accessible for general audience. For me, that was perfect for casual reading.\n\nI was unaware of just how many types of dinosaurs there were. Not to mention the "not a dinosaur but basically a dinosaur except classification" ones. I\'ve practically forgotten them all since completing the book.\n\nBut I did take away a wonderful curiosity for our modern day dinosaurs. Birds. As well as an admiration for how paleontologists know what they know. As a schoolkid, you\'re always either told "facts" or told "scientific theories", but never explained where these came from.\n\nTo understand you can look at a dinosaurs bones and "count the rings" in idiot-speak (which I need) to count the age, that\'s fascinating. I really enjoyed the explanations of why we know the history, as much as, if not more than the actual history itself. And the book did a great job of explaining that in a way that I could understand.',
    description: 'The dinosaurs. Sixty-six million years ago, the Earth\'s most fearsome creatures vanished. Today they remain one of our planet\'s great mysteries. Now The Rise and Fall of the Dinosaurs reveals their extraordinary, 200-million-year-long story as never before.\n\nIn this captivating narrative (enlivened with more than seventy original illustrations and photographs), Steve Brusatte, a young American paleontologist who has emerged as one of the foremost stars of the field—naming fifteen new species and leading groundbreaking scientific studies and fieldwork—masterfully tells the complete, surprising, and new history of the dinosaurs, drawing on cutting-edge science to dramatically bring to life their lost world and illuminate their enigmatic origins, spectacular flourishing, astonishing diversity, cataclysmic extinction, and startling living legacy.\n\nBrusatte traces the evolution of dinosaurs from their inauspicious start as small shadow dwellers into the dominant array of species every wide-eyed child memorizes today, T. rex, Triceratops, Brontosaurus, and more. He re-creates the dinosaurs\' peak during the Jurassic and Cretaceous, when thousands of species thrived, and winged and feathered dinosaurs, the prehistoric ancestors of modern birds, emerged. The story continues to the end of the Cretaceous period, when a giant asteroid or comet struck the planet and nearly every dinosaur species (but not all) died out, in the most extraordinary extinction event in earth\'s history.',
  },
  {
    id: '43',
    title: 'Revenger',
    author: 'Alastair Reynolds',
    readDate: '2026-08-14',
    isbn: 9780316555562,
    type: 'print',
    numberOfPages: 425,
    genres: ['Science Fiction'],
    rating: 3.2,
    review: 'You know how some people have phases of drunken nights? This book had clear phases for me.\n\n1) What on earth are all these terms?? Okay, keep reading, I guess he\'ll explain.\n2) Ohhh this is a YA book (for teens)?\n3) Wow, damn. That\'s dark. Maybe it\'s not.\n4) Nope, it definitely is.\n5) Ok now I need to know what happens.\n\nThe 5th point is really just me, I don\'t do well with incomplete stories. If I want to stop watching a TV show, I need to read up the spoilers so I can stop it. Even if it sucks.\n\nI\'d sum up this book saying it was fun to read. But far from a favourite, pretty bottom tier of sci-fi for me. Not Hyperion, ugh, I hated how that was written. But just okay… Like a Netflix released movie. Did the job for what it was.',
    description: 'The galaxy has seen great empires rise and fall. Planets have shattered and been remade. Amongst the ruins of alien civilizations, building our own from the rubble, humanity still thrives. And there are vast fortunes to be made, if you know where to find them.\n\nCaptain Rackamore and his crew do. It\'s their business to find the tiny, enigmatic worlds which have been hidden away, booby-trapped, surrounded by layers of protection—and to crack them open for the ancient relics and barely-remembered technologies inside. But while they ply their risky trade with integrity, not everyone is so scrupulous.\n\nAdrana and Fura Ness are the newest members of Rackamore\'s crew, signed on to save their family from bankruptcy. Only Rackamore has enemies, and there might be more waiting for them in space than adventure and fortune: the fabled and feared Bosa Sennen in particular.\n\nRevenger is a science fiction adventure story set in the rubble of our solar system in the dark, distant future—a tale of space pirates, buried treasure, and phantom weapons, of unspeakable hazards and single-minded heroism, and of vengeance.',
  },
  {
    id: '44',
    title: 'Life 3.0: Being Human in the Age of Artificial Intelligence',
    author: 'Max Tegmark',
    readDate: '2026-08-26',
    isbn: 9780451485083,
    type: 'audio',
    numberOfPages: 384,
    durationHours: 13,
    durationMinutes: 29,
    genres: ['Science', 'Technology'],
    rating: 3.7,
    review: 'I\'ve had this audiobook sitting in my Audible library for ages. Finally got round to listening and it\'s… interesting. Nothing on the level of Bennett\'s "A Brief History of Intelligence". But interesting, I guess.\n\nThe first chapter, I may have missed the memo on it being fiction. I was amazed and had no idea there was any company making money from mTurk with AI to that level, it seemed absurd. And as it continued, I realised it was absurd as the story became incredibly implausible. Could it be possible one day? Maybe. But I got his point.\n\nThis is essentially a book about AI safety. Looking at the possibilities and dangers as it continues to improve into the future. I agree with most of his points. Build first, dial in safety later is not only a terrible idea for AI, it may be impossible to do once it\'s out there.\n\nI\'d say this book became progressively more dull as I read it. The fictional intro was actually rather fun to ponder. His thesis on life 1.0, life 2.0, and a future life 3.0 is fascinating. It\'s just, idk, bit fluffy? Audiobooks don\'t help here, but I could easily tune out for parts because it felt like he was saying nothing.\n\nWould I recommend it? Not unless you\'re very into this topic and would like to read different perspectives on it.',
    description: 'How will Artificial Intelligence affect crime, war, justice, jobs, society and our very sense of being human? The rise of AI has the potential to transform our future more than any other technology—and there\'s nobody better qualified or situated to explore that future than Max Tegmark, an MIT professor who\'s helped mainstream research on how to keep AI beneficial.\n\nHow can we grow our prosperity through automation without leaving people lacking income or purpose? What career advice should we give today\'s kids? How can we make future AI systems more robust, so that they do what we want without crashing, malfunctioning or getting hacked? Should we fear an arms race in lethal autonomous weapons? Will machines eventually outsmart us at all tasks, replacing humans on the job market and perhaps altogether? Will AI help life flourish like never before or give us more power than we can handle?\n\nWhat sort of future do you want? This book empowers you to join what may be the most important conversation of our time. It doesn\'t shy away from the full range of viewpoints or from the most controversial issues—from superintelligence to meaning, consciousness and the ultimate physical limits on life in the cosmos.',
  },
];
